-- The data for the following tables we received along with the BSHT data
-- BEGIN LU_Tables from BSHT DVD5
CREATE TABLE LU_DAYMAP
(
  DAYMAP_ID           NUMERIC(2) NOT NULL,
  DAYMAP              CHAR(8) NOT NULL,
  DAYTYPE_ID          NUMERIC(1) NOT NULL,
  LEGACYFREQUENCYCODE NUMERIC(2),
  COMMENTS            VARCHAR(255),
  NEXTDAYID           NUMERIC(1)
);

COPY LU_DAYMAP FROM 's3://cta-data/lu_tables/LU_DAYMAP.txt.fix'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_DAYMAP2
(
  DAYTYPEID NUMERIC(1) NOT NULL,
  DAYMAP_ID NUMERIC(2)
);

COPY LU_DAYMAP2 FROM 's3://cta-data/lu_tables/LU_DAYMAP2.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_DAYTYPE
(
  DAYTYPEID NUMERIC NOT NULL,
  DAYNAME   VARCHAR(9)
);

COPY LU_DAYTYPE FROM 's3://cta-data/lu_tables/LU_DAYTYPE.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_DIR
(
  DIR_ID      NUMERIC(2) NOT NULL,
  DIR         VARCHAR(3) NOT NULL,
  MINHEADING  NUMERIC(3) NOT NULL,
  MAXHEADING  NUMERIC(3) NOT NULL,
  DESCRIPTION VARCHAR(5)
);

COPY LU_DIR FROM 's3://cta-data/lu_tables/LU_DIR.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_DIRECTION
(
  DIRECTION_ID NUMERIC(2) NOT NULL,
  DIRECTION    VARCHAR(16) NOT NULL,
  SHORTDIR     VARCHAR(2),
  DIR_GROUP    NUMERIC(1)
);

COPY LU_DIRECTION FROM 's3://cta-data/lu_tables/LU_DIRECTION.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_EVENT
(
  EVENT_ID NUMERIC,
  EVENT    VARCHAR(20)
);

COPY LU_EVENT FROM 's3://cta-data/lu_tables/LU_EVENT.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_ROUTE
(
  ROUTE_ID       INTEGER NOT NULL,
  ROUTESORT      VARCHAR(5) NOT NULL,
  ROUTE          VARCHAR(4) NOT NULL,
  NAME           VARCHAR(255) NOT NULL,
  ROUTETYPE_ID   NUMERIC(1) NOT NULL,
  LIFT           NUMERIC(1) NOT NULL,
  OWL            NUMERIC(1) NOT NULL,
  TITLE6         NUMERIC(1) NOT NULL,
  GARAGE_ID      NUMERIC(1),
  GARAGE2_ID     NUMERIC(1),
  HASTUS_ROUTEID VARCHAR(5),
  MH_KEY         NUMERIC(1),
  AFCROUTE       NUMERIC(3)
);

COPY LU_ROUTE FROM 's3://cta-data/lu_tables/LU_ROUTE.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_ROUTESTATUS
(
  ROUTESTATUS_ID   NUMERIC(2),
  ROUTESTATUS_DESC VARCHAR(20)
);

COPY LU_ROUTESTATUS FROM 's3://cta-data/lu_tables/LU_ROUTESTATUS.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_ROUTETYPE
(
  ROUTETYPE_ID   NUMERIC(2) NOT NULL,
  ROUTETYPE_DESC VARCHAR(20)
);

COPY LU_ROUTETYPE FROM 's3://cta-data/lu_tables/LU_ROUTETYPE.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_SCHDTYP
(
  SCHDTYPID      NUMERIC NOT NULL,
  CTA_SCHD       VARCHAR(15),
  DAY_TYPE1      VARCHAR(1),
  DAY_TYPE2      VARCHAR(2),
  DAY_TYPE3      VARCHAR(3),
  DAY_TYPE_NAME  VARCHAR(9),
  DAY_TYPE_NAMES VARCHAR(9),
  DAY_TYPE_LONG  VARCHAR(20)
);

COPY LU_SCHDTYP FROM 's3://cta-data/lu_tables/LU_SCHDTYP.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_TIMEPERIOD
(
  TIMEPERIODID NUMERIC NOT NULL,
  TIMEPERIOD   VARCHAR(10),
  STARTTIME    VARCHAR(8),
  ENDTIME      VARCHAR(8),
  MINSECONDS   NUMERIC(6),
  MAXSECONDS   NUMERIC(6),
  RT_FACTOR    NUMERIC(2),
  PEAK         NUMERIC(2)
);

COPY LU_TIMEPERIOD FROM 's3://cta-data/lu_tables/LU_TIMEPERIOD.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_TIMEPOINTSTATUS
(
  TIMEPOINTSTATUS_ID   NUMERIC(2) NOT NULL,
  TIMEPOINTSTATUS_DESC VARCHAR(30)
);

COPY LU_TIMEPOINTSTATUS FROM 's3://cta-data/lu_tables/LU_TIMEPOINTSTATUS.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_TIMEPOINTTYPE
(
  TIMEPOINTTYPE_ID   NUMERIC(2) NOT NULL,
  TIMEPOINTTYPE_DESC VARCHAR(50)
);

COPY LU_TIMEPOINTTYPE FROM 's3://cta-data/lu_tables/LU_TIMEPOINTTYPE.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_TRIPTYPE
(
  TRIPTYPE_ID NUMERIC(1) NOT NULL,
  TRIPTYPE    VARCHAR(50)
);

COPY LU_TRIPTYPE FROM 's3://cta-data/lu_tables/LU_TRIPTYPE.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE LU_WORKSTATUS
(
  WORKSTATUS_ID   NUMERIC(2) NOT NULL,
  WORKSTATUS_DESC VARCHAR(50)
);

COPY LU_WORKSTATUS FROM 's3://cta-data/lu_tables/LU_WORKSTATUS.txt.fix'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;
-- END LU_Tables from BSHT DVD5

-- We received the following tables via email in Excel files
-- BEGIN LU_Tables from email communications
CREATE TABLE LU_DAY
(
  DAY_ID     NUMERIC(6),
  JULIANDATE NUMERIC(7),
  MMDDYYYY   DATE,
  ADATE      VARCHAR(10),
  AMONTH     NUMERIC(2),
  ADAY       NUMERIC(2),
  AYEAR      NUMERIC(4),
  DAYTYPEID  NUMERIC(1),
  DAYNAME    VARCHAR(10),
  SCHDID     NUMERIC(1),
  CTA_SCHD   VARCHAR(15),
  HOLIDAYID  NUMERIC(2),
  HOLIDAY    VARCHAR
);

COPY LU_DAY FROM 's3://cta-data/ex_tables/LU_DAY.csv'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL
DATEFORMAT AS 'MM-DD-YYYY';

CREATE TABLE LU_CTRL_PT
(
  TAROUTE      VARCHAR(5) NOT NULL,
  ROUTE_NUMBER NUMERIC(6,1),
  DIRECTION    VARCHAR(16) NOT NULL,
  DIRECTION_ID NUMERIC(2) NOT NULL,
  PLACEID      VARCHAR(50)
)
SORTKEY(TAROUTE,DIRECTION_ID);

COPY LU_CTRL_PT FROM 's3://cta-data/ex_tables/LU_CTRL_PT.csv'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

-- END LU_Tables from email communications
