CREATE TABLE rcp_master
(
 serial_number              NUMERIC(11) not null,
 schedule_id                NUMERIC(11),
 schedule_name              VARCHAR(50),
 signup_name                VARCHAR(50),
 protected                  NUMERIC(1) default 0,
 archived                   NUMERIC(1) default 0,
 handheld_name              VARCHAR(50),
 handheld_number            NUMERIC(11),
 handheld_timestamp         TIMESTAMP,
 application_timestamp      TIMESTAMP,
 handheld_done              NUMERIC(1) default 0,
 distinct_trip              NUMERIC(1) default 0,
 survey_status              NUMERIC(3) default 1,
 survey_type                NUMERIC(3) default 1,
 survey_source              NUMERIC(3) default 1,
 pattern_id                 NUMERIC(11),
 branch                     VARCHAR(50),
 route_number               NUMERIC(6,1),
 route_name                 VARCHAR(50),
 direction_name             VARCHAR(50),
 service_code               VARCHAR(50),
 service_type               VARCHAR(50),
 service_mode               VARCHAR(50),
 survey_date                DATE,
 survey_date_effective      DATE,
 survey_date_atypical       NUMERIC(1) default 0,
 trip_start_time            TIMESTAMP,
 trip_end_time              TIMESTAMP,
 next_day                   NUMERIC(1) default 0,
 time_period                VARCHAR(50),
 service_day                NUMERIC(3),
 service_period             VARCHAR(50),
 trip_number                NUMERIC(11),
 trip_key                   NUMERIC(11),
 block_number               NUMERIC(11),
 block_key                  VARCHAR(50),
 run_number                 NUMERIC(11),
 run_key                    VARCHAR(50),
 operator_id                NUMERIC(11),
 vehicle_number             NUMERIC(11),
 vehicle_description        VARCHAR(50),
 vehicle_seats              NUMERIC(11),
 garage_id                  NUMERIC(11),
 garage_name                VARCHAR(50),
 division_id                NUMERIC(11),
 division_name              VARCHAR(50),
 revenue_start              FLOAT4,
 revenue_end                FLOAT4,
 revenue_net                FLOAT4,
 odom_start                 FLOAT4,
 odom_end                   FLOAT4,
 odom_net                   FLOAT4,
 condition_number           NUMERIC(3) default 0,
 checker_id                 NUMERIC(11),
 checker_name               VARCHAR(50),
 revenue_miles              FLOAT4,
 revenue_hours              FLOAT4,
 actual_start_time          TIMESTAMP,
 actual_end_time            TIMESTAMP,
 total_passengers_on        FLOAT4,
 total_passengers_off       FLOAT4,
 total_passengers_in        FLOAT4,
 total_passenger_miles      FLOAT4,
 total_seat_miles           FLOAT4,
 max_load                   FLOAT4,
 max_load_p                 FLOAT4,
 pass_per_mile              FLOAT4,
 pass_per_hour              FLOAT4,
 tp_ontime                  NUMERIC(11),
 tp_early                   NUMERIC(11),
 tp_late                    NUMERIC(11),
 ontime                     FLOAT4,
 ontime_diff_avg            FLOAT4,
 dwell_time_avg             FLOAT4,
 scheduled_speed            FLOAT4,
 actual_speed               FLOAT4,
 total_stops                NUMERIC(11),
 requires_update            NUMERIC(1) default -1,
 last_update                TIMESTAMP default TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS'),
 comments                   VARCHAR(4000),
 trip_count                 NUMERIC(11),
 new_survey                 NUMERIC(1) default -1,
 distinct_trip_avl          NUMERIC(1) default 0,
 total_wheelchairs          NUMERIC(11),
 pullin_time_scheduled      TIMESTAMP,
 pullin_time_actual         TIMESTAMP,
 pullout_time_scheduled     TIMESTAMP,
 pullout_time_actual        TIMESTAMP,
 trip_id                    NUMERIC(11),
 total_demog_01             FLOAT4,
 total_demog_02             FLOAT4,
 total_demog_03             FLOAT4,
 total_demog_04             FLOAT4,
 total_demog_05             FLOAT4,
 total_demog_06             FLOAT4,
 total_demog_07             FLOAT4,
 total_demog_08             FLOAT4,
 total_demog_09             FLOAT4,
 total_demog_10             FLOAT4,
 total_demog_11             FLOAT4,
 total_demog_12             FLOAT4,
 total_demog_13             FLOAT4,
 total_demog_14             FLOAT4,
 total_demog_15             FLOAT4,
 total_demog_16             FLOAT4,
 total_demog_17             FLOAT4,
 total_demog_18             FLOAT4,
 total_demog_19             FLOAT4,
 total_demog_20             FLOAT4,
 total_demog_21             FLOAT4,
 total_demog_22             FLOAT4,
 total_demog_23             FLOAT4,
 total_demog_24             FLOAT4,
 total_demog_25             FLOAT4,
 time_period_sort           NUMERIC(1),
 min_load                   FLOAT4,
 farebox                    NUMERIC(11),
 supervisor_attn            NUMERIC(1) default 0,
 non_student_fare           NUMERIC(11),
 match_count                NUMERIC(11),
 service_class              VARCHAR(50),
 start_load                 FLOAT4,
 end_load                   FLOAT4,
 total_fon                  NUMERIC(11),
 total_foff                 NUMERIC(11),
 total_ron                  NUMERIC(11),
 total_roff                 NUMERIC(11),
 type_avlcheck              NUMERIC(1),
 type_farecheck             NUMERIC(1),
 type_ridecheck             NUMERIC(1) default -1,
 trip_count_avlcheck        NUMERIC(1),
 trip_count_farecheck       NUMERIC(1),
 trip_count_ridecheck       NUMERIC(1),
 pattern_key                VARCHAR(50),
 total_demog_sum            FLOAT4,
 standing_area              NUMERIC(11,5),
 deadhead_minutes_scheduled FLOAT4,
 layover_minutes_scheduled  FLOAT4,
 transaction_rollup_id      NUMERIC(11),
 total_demog_26             FLOAT4,
 total_demog_27             FLOAT4,
 checker_after_minutes      NUMERIC(11) default 0,
 checker_before_minutes     NUMERIC(11) default 0,
 temperature                NUMERIC(11),
 block_id                   NUMERIC(11),
 type_odcheck               NUMERIC(1) default 0,
 assignment                 VARCHAR(50),
 total_bicycles             NUMERIC(11),
 total_kneels               NUMERIC(11),
 actual_start_time_before   TIMESTAMP,
 actual_end_time_after      TIMESTAMP,
 start_timepoint            VARCHAR(50),
 end_timepoint              VARCHAR(50),
 onboard_software_version   VARCHAR(50),
 schedule_software_version  VARCHAR(50),
 load_duration              FLOAT4,
 load_duration_alt          FLOAT4,
 total_traffic_priority     NUMERIC(11),
 layover_minutes_actual     FLOAT4,
 deadhead_minutes_actual    FLOAT4,
 route_name_alt             VARCHAR(50),
 PRIMARY KEY(serial_number)
)
DISTKEY(serial_number)
SORTKEY(serial_number);

COPY rcp_master FROM 's3://cta-data/rcp_uc2/master'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL
TIMEFORMAT AS 'MM/DD/YYYY HH12:MI:SS PM'
DATEFORMAT AS 'MM/DD/YYYY';

