-- The data for the following tables we received along with the BSHT data
-- BEGIN BT_Tables from BSHT DVD5
CREATE TABLE BT_PATTERN
(
  BT_VER      NUMERIC(3) NOT NULL,
  PATTERNID   NUMERIC(5) NOT NULL,
  TAROUTE     VARCHAR(5),
  PATTERNNAME VARCHAR(50),
  DIRECTION   NUMERIC(2),
  DISTANCE    NUMERIC(6),
  ROUTE       CHAR(5),
  PATTERN     CHAR(2),
  PATTERNDESC VARCHAR(60),
  ROUTETXT    VARCHAR(32)
  PRIMARY KEY(BT_VER,PATTERNID)
)
DISTKEY(BT_VER)
SORTKEY(BT_VER,TAROUTE,DIRECTION);

COPY BT_PATTERN FROM 's3://cta-data/bt_tables/BT_PATTERN.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_PATTERNDETAIL
(
  BT_VER        NUMERIC(3),
  PATTERNID     NUMERIC(5),
  GEOID         NUMERIC(5),
  STOPID        NUMERIC(5),
  TIMEPOINTID   NUMERIC(4),
  DISTANCE      NUMERIC(9),
  PATTERNORDER  NUMERIC(3),
  SORTORDER     NUMERIC(9),
  STOPSORTORDER NUMERIC(3)
)
DISTKEY(BT_VER)
SORTKEY(BT_VER,PATTERNID,GEOID);

COPY BT_PATTERNDETAIL FROM 's3://cta-data/bt_tables/BT_PATTERNDETAIL.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_S_VERSION
(
  S_VER         NUMERIC(2) NOT NULL,
  SIGNUPNAME    VARCHAR(50) NOT NULL,
  SIGNUPVERSION NUMERIC(1) NOT NULL,
  NOTES         VARCHAR(200),
  STARTDATE     DATE,
  ENDDATE       DATE,
  ACTIVE        NUMERIC(1),
  RTAVAILABLE   NUMERIC(1),
  NOTES2        VARCHAR(200),
  RBS_VER       VARCHAR(15),
  PRIMARY KEY(S_VER)
)
DISTKEY(S_VER)
SORTKEY(S_VER,STARTDATE,ENDDATE);

COPY BT_S_VERSION FROM 's3://cta-data/bt_tables/BT_S_VERSION.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL
DATEFORMAT AS 'DD-MON-YY';

CREATE TABLE BT_STOP
(
  BT_VER         NUMERIC(3),
  GEOID          NUMERIC(6),
  GEODESCRIPTION VARCHAR(50),
  TAGEOID        VARCHAR(6),
  LONGITUDE      FLOAT,
  LATITUDE       FLOAT,
  HEADING        NUMERIC(5,2)
)
DISTKEY(BT_VER)
SORTKEY(BT_VER,GEOID);

COPY BT_STOP FROM 's3://cta-data/bt_tables/BT_STOP.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_STOPDESC
(
  BT_VER   NUMERIC(3),
  TAGEOID  VARCHAR(6),
  STOPDESC VARCHAR(80),
  ENABLED  NUMERIC(1)
);

COPY BT_STOPDESC FROM 's3://cta-data/bt_tables/BT_STOPDESC.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_STOPINFO
(
  BT_VER   NUMERIC(3),
  STOPID   NUMERIC(5),
  STOPDESC VARCHAR(50)
);

COPY BT_STOPINFO FROM 's3://cta-data/bt_tables/BT_STOPINFO.txt.fix'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_TERMINAL
(
  BT_VER            NUMERIC(3) NOT NULL,
  TERMINALID        NUMERIC(3) NOT NULL,
  BTPLACEID         NUMERIC(3),
  DEPOTCIRCLERADIUS NUMERIC(5),
  NAME              VARCHAR(10),
  GEODESCRIPTION    VARCHAR(50),
  REASON1           VARCHAR(50),
  REASON2           VARCHAR(50),
  CREATOR           VARCHAR(50)
);

COPY BT_TERMINAL FROM 's3://cta-data/bt_tables/BT_TERMINAL.txt.fix'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_TIMEPOINT
(
  BT_VER      NUMERIC(3),
  TIMEPOINTID NUMERIC(4),
  PLACEID     VARCHAR(50),
  DESCRIPTION VARCHAR(50),
  LATITUDE    FLOAT,
  LONGITUDE   FLOAT
)
DISTKEY(BT_VER)
SORTKEY(BT_VER,TIMEPOINTID);

COPY BT_TIMEPOINT FROM 's4://cta-data/bt_tables/BT_TIMEPOINT.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_TIMEPOINTDIST
(
  BT_VER    NUMERIC(3) NOT NULL,
  PATTERNID NUMERIC(5) NOT NULL,
  FROM_TP   VARCHAR(50) NOT NULL,
  TO_TP     VARCHAR(50) NOT NULL,
  DIST      NUMERIC
);

COPY BT_TIMEPOINTDIST FROM 's3://cta-data/bt_tables/BT_TIMEPOINTDIST.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_TRIP2
(
  S_VER        NUMERIC(2),
  TRIPNO       NUMERIC(8),
  PATTERNID    NUMERIC(5),
  TRIPTYPE     NUMERIC(1),
  SCHEDULETYPE NUMERIC(1),
  REVENUE      NUMERIC(1),
  BLOCKNO      NUMERIC(7),
  BLOCKID      VARCHAR(10),
  DAYMAP       NUMERIC(2),
  TRIPID       VARCHAR(15),
  TRIPSTART    NUMERIC(22),
  TRIPEND      NUMERIC(22),
  GUZINTO      NUMERIC(1),
  TPSTART      VARCHAR(6),
  TPEND        VARCHAR(6)
)
DISTKEY(S_VER)
SORTKEY(S_VER,TRIPNO,TRIPSTART);

COPY BT_TRIP2 FROM 's3://cta-data/bt_tables/BT_TRIP2.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL;

CREATE TABLE BT_TRIPDETAIL
(
  S_VER       NUMERIC(2),
  TRIPNO      NUMERIC(8),
  TIMEPOINTID NUMERIC(4),
  PASSINGTIME DATE,
  TIMESEC     NUMERIC(6),
  RUNID       CHAR(4),
  GARAGE      CHAR(1),
  SHORTRUNNO  NUMERIC(3)
);

COPY BT_TRIPDETAIL FROM 's3://cta-data/bt_tables/BT_TRIPDETAIL.txt'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL
DATEFORMAT AS 'DD-MON-YY';

CREATE TABLE BT_VERSION
(
  BT_VER           NUMERIC(3),
  S_VER            NUMERIC(3),
  NOTES            VARCHAR(200),
  DISTRIBUTIONDATE DATE,
  ACTIVE           NUMERIC(1),
  PASSINGTIME      NUMERIC(1)
);

COPY BT_VERSION FROM 's3://cta-data/bt_tables/BT_VERSION.txt.fix'
CREDENTIALS 'aws_access_key_id=$[AWS_ACCESS_KEY_ID];aws_secret_access_key=$[AWS_SECRET_ACCESS_KEY]'
DELIMITER AS ','
EMPTYASNULL
DATEFORMAT AS 'DD-MON-YY';
-- END BT_Tables from BSHT DVD5
