function webapp(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Gb='.cache.html',_='/',Fb=':',ob='::',Tb='<script defer="defer">webapp.onInjectionDone(\'webapp\')<\/script>',hb='<script id="',Pb='<script language="javascript" src="',rb='=',$='?',tb='Bad handler "',Nb='DOMContentLoaded',Eb="GWT module 'webapp' may need to be (re)compiled",jb='SCRIPT',gb='__gwt_marker_webapp',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Y='end',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Mb='head',Cb='hosted.html?webapp',Lb='href',xb='iframe',ab='img',yb="javascript:''",Ob='js/ext/adapter/ext/ext-base.js',Qb='js/ext/adapter/ext/ext-base.js"><\/script>',Rb='js/ext/ext-all.js',Sb='js/ext/ext-all.js"><\/script>',Hb='js/ext/resources/css/ext-all.css',Ib='link',Bb='loadExternalRefs',lb='meta',Ab='moduleRequested',X='moduleStartup',mb='name',zb='position:absolute;width:0;height:0;border:none',Jb='rel',db='script',Db='selectingPermutation',R='startup',Kb='stylesheet',fb='undefined',Q='webapp',eb='webapp.nocache.js',nb='webapp::';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}webapp=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function F(a){var b=t[a];return b==null?null:b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
webapp.onScriptLoad=function(){if(I){q=true;B()}};webapp.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Bb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Cb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Db});if(!A()){try{alert(Eb);return;var M=K.indexOf(Fb);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+Gb}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[Hb]){var a=m.createElement(Ib);__gwt_stylesLoaded[Hb]=a;a.setAttribute(Jb,Kb);a.setAttribute(Lb,s+Hb);m.getElementsByTagName(Mb)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Nb,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Nb,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Bb,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[Ob]){__gwt_scriptsLoaded[Ob]=true;document.write(Pb+s+Qb)}if(!__gwt_scriptsLoaded[Rb]){__gwt_scriptsLoaded[Rb]=true;document.write(Pb+s+Sb)}m.write(Tb)}
webapp();